// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

#ifndef PROTOBUF_job_2eproto__INCLUDED
#define PROTOBUF_job_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cjtech {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_job_2eproto();
void protobuf_AssignDesc_job_2eproto();
void protobuf_ShutdownFile_job_2eproto();

class Job;

// ===================================================================

class Job : public ::google::protobuf::Message {
 public:
  Job();
  virtual ~Job();

  Job(const Job& from);

  inline Job& operator=(const Job& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Job& default_instance();

  void Swap(Job* other);

  // implements Message ----------------------------------------------

  Job* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Job& from);
  void MergeFrom(const Job& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 task_id = 1;
  inline bool has_task_id() const;
  inline void clear_task_id();
  static const int kTaskIdFieldNumber = 1;
  inline ::google::protobuf::int32 task_id() const;
  inline void set_task_id(::google::protobuf::int32 value);

  // required int32 job_type = 2;
  inline bool has_job_type() const;
  inline void clear_job_type();
  static const int kJobTypeFieldNumber = 2;
  inline ::google::protobuf::int32 job_type() const;
  inline void set_job_type(::google::protobuf::int32 value);

  // required int32 content_type = 3;
  inline bool has_content_type() const;
  inline void clear_content_type();
  static const int kContentTypeFieldNumber = 3;
  inline ::google::protobuf::int32 content_type() const;
  inline void set_content_type(::google::protobuf::int32 value);

  // required int32 content_length = 4;
  inline bool has_content_length() const;
  inline void clear_content_length();
  static const int kContentLengthFieldNumber = 4;
  inline ::google::protobuf::int32 content_length() const;
  inline void set_content_length(::google::protobuf::int32 value);

  // required int64 start_time_ = 5;
  inline bool has_start_time_() const;
  inline void clear_start_time_();
  static const int kStartTimeFieldNumber = 5;
  inline ::google::protobuf::int64 start_time_() const;
  inline void set_start_time_(::google::protobuf::int64 value);

  // required int64 end_time = 6;
  inline bool has_end_time() const;
  inline void clear_end_time();
  static const int kEndTimeFieldNumber = 6;
  inline ::google::protobuf::int64 end_time() const;
  inline void set_end_time(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cjtech.Job)
 private:
  inline void set_has_task_id();
  inline void clear_has_task_id();
  inline void set_has_job_type();
  inline void clear_has_job_type();
  inline void set_has_content_type();
  inline void clear_has_content_type();
  inline void set_has_content_length();
  inline void clear_has_content_length();
  inline void set_has_start_time_();
  inline void clear_has_start_time_();
  inline void set_has_end_time();
  inline void clear_has_end_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 task_id_;
  ::google::protobuf::int32 job_type_;
  ::google::protobuf::int32 content_type_;
  ::google::protobuf::int32 content_length_;
  ::google::protobuf::int64 start_time__;
  ::google::protobuf::int64 end_time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_job_2eproto();
  friend void protobuf_AssignDesc_job_2eproto();
  friend void protobuf_ShutdownFile_job_2eproto();

  void InitAsDefaultInstance();
  static Job* default_instance_;
};
// ===================================================================


// ===================================================================

// Job

// required int32 task_id = 1;
inline bool Job::has_task_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Job::set_has_task_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Job::clear_has_task_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Job::clear_task_id() {
  task_id_ = 0;
  clear_has_task_id();
}
inline ::google::protobuf::int32 Job::task_id() const {
  return task_id_;
}
inline void Job::set_task_id(::google::protobuf::int32 value) {
  set_has_task_id();
  task_id_ = value;
}

// required int32 job_type = 2;
inline bool Job::has_job_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Job::set_has_job_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Job::clear_has_job_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Job::clear_job_type() {
  job_type_ = 0;
  clear_has_job_type();
}
inline ::google::protobuf::int32 Job::job_type() const {
  return job_type_;
}
inline void Job::set_job_type(::google::protobuf::int32 value) {
  set_has_job_type();
  job_type_ = value;
}

// required int32 content_type = 3;
inline bool Job::has_content_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Job::set_has_content_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Job::clear_has_content_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Job::clear_content_type() {
  content_type_ = 0;
  clear_has_content_type();
}
inline ::google::protobuf::int32 Job::content_type() const {
  return content_type_;
}
inline void Job::set_content_type(::google::protobuf::int32 value) {
  set_has_content_type();
  content_type_ = value;
}

// required int32 content_length = 4;
inline bool Job::has_content_length() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Job::set_has_content_length() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Job::clear_has_content_length() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Job::clear_content_length() {
  content_length_ = 0;
  clear_has_content_length();
}
inline ::google::protobuf::int32 Job::content_length() const {
  return content_length_;
}
inline void Job::set_content_length(::google::protobuf::int32 value) {
  set_has_content_length();
  content_length_ = value;
}

// required int64 start_time_ = 5;
inline bool Job::has_start_time_() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Job::set_has_start_time_() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Job::clear_has_start_time_() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Job::clear_start_time_() {
  start_time__ = GOOGLE_LONGLONG(0);
  clear_has_start_time_();
}
inline ::google::protobuf::int64 Job::start_time_() const {
  return start_time__;
}
inline void Job::set_start_time_(::google::protobuf::int64 value) {
  set_has_start_time_();
  start_time__ = value;
}

// required int64 end_time = 6;
inline bool Job::has_end_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Job::set_has_end_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Job::clear_has_end_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Job::clear_end_time() {
  end_time_ = GOOGLE_LONGLONG(0);
  clear_has_end_time();
}
inline ::google::protobuf::int64 Job::end_time() const {
  return end_time_;
}
inline void Job::set_end_time(::google::protobuf::int64 value) {
  set_has_end_time();
  end_time_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cjtech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_job_2eproto__INCLUDED
