// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProInnerMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ProInnerMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace leopardIO {

namespace {

const ::google::protobuf::Descriptor* ProInnerMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProInnerMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProInnerMessage_2eproto() {
  protobuf_AddDesc_ProInnerMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProInnerMessage.proto");
  GOOGLE_CHECK(file != NULL);
  ProInnerMessage_descriptor_ = file->message_type(0);
  static const int ProInnerMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, session_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, message_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, content_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, content_length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, start_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, end_time_),
  };
  ProInnerMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ProInnerMessage_descriptor_,
      ProInnerMessage::default_instance_,
      ProInnerMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProInnerMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ProInnerMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProInnerMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ProInnerMessage_descriptor_, &ProInnerMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ProInnerMessage_2eproto() {
  delete ProInnerMessage::default_instance_;
  delete ProInnerMessage_reflection_;
}

void protobuf_AddDesc_ProInnerMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025ProInnerMessage.proto\022\tleopardIO\"\217\001\n\017P"
    "roInnerMessage\022\022\n\nsession_id\030\001 \002(\005\022\024\n\014me"
    "ssage_type\030\002 \002(\005\022\024\n\014content_type\030\003 \002(\005\022\026"
    "\n\016content_length\030\004 \002(\005\022\022\n\nstart_time\030\005 \002"
    "(\002\022\020\n\010end_time\030\006 \002(\002", 180);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProInnerMessage.proto", &protobuf_RegisterTypes);
  ProInnerMessage::default_instance_ = new ProInnerMessage();
  ProInnerMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProInnerMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProInnerMessage_2eproto {
  StaticDescriptorInitializer_ProInnerMessage_2eproto() {
    protobuf_AddDesc_ProInnerMessage_2eproto();
  }
} static_descriptor_initializer_ProInnerMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ProInnerMessage::kSessionIdFieldNumber;
const int ProInnerMessage::kMessageTypeFieldNumber;
const int ProInnerMessage::kContentTypeFieldNumber;
const int ProInnerMessage::kContentLengthFieldNumber;
const int ProInnerMessage::kStartTimeFieldNumber;
const int ProInnerMessage::kEndTimeFieldNumber;
#endif  // !_MSC_VER

ProInnerMessage::ProInnerMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ProInnerMessage::InitAsDefaultInstance() {
}

ProInnerMessage::ProInnerMessage(const ProInnerMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ProInnerMessage::SharedCtor() {
  _cached_size_ = 0;
  session_id_ = 0;
  message_type_ = 0;
  content_type_ = 0;
  content_length_ = 0;
  start_time_ = 0;
  end_time_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProInnerMessage::~ProInnerMessage() {
  SharedDtor();
}

void ProInnerMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ProInnerMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProInnerMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProInnerMessage_descriptor_;
}

const ProInnerMessage& ProInnerMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ProInnerMessage_2eproto();
  return *default_instance_;
}

ProInnerMessage* ProInnerMessage::default_instance_ = NULL;

ProInnerMessage* ProInnerMessage::New() const {
  return new ProInnerMessage;
}

void ProInnerMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    session_id_ = 0;
    message_type_ = 0;
    content_type_ = 0;
    content_length_ = 0;
    start_time_ = 0;
    end_time_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ProInnerMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 session_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &session_id_)));
          set_has_session_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_message_type;
        break;
      }

      // required int32 message_type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_message_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_type_)));
          set_has_message_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_content_type;
        break;
      }

      // required int32 content_type = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_content_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &content_type_)));
          set_has_content_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_content_length;
        break;
      }

      // required int32 content_length = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_content_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &content_length_)));
          set_has_content_length();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_start_time;
        break;
      }

      // required float start_time = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_start_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &start_time_)));
          set_has_start_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_end_time;
        break;
      }

      // required float end_time = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_end_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &end_time_)));
          set_has_end_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ProInnerMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 session_id = 1;
  if (has_session_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->session_id(), output);
  }

  // required int32 message_type = 2;
  if (has_message_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->message_type(), output);
  }

  // required int32 content_type = 3;
  if (has_content_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->content_type(), output);
  }

  // required int32 content_length = 4;
  if (has_content_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->content_length(), output);
  }

  // required float start_time = 5;
  if (has_start_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->start_time(), output);
  }

  // required float end_time = 6;
  if (has_end_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->end_time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ProInnerMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 session_id = 1;
  if (has_session_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->session_id(), target);
  }

  // required int32 message_type = 2;
  if (has_message_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->message_type(), target);
  }

  // required int32 content_type = 3;
  if (has_content_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->content_type(), target);
  }

  // required int32 content_length = 4;
  if (has_content_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->content_length(), target);
  }

  // required float start_time = 5;
  if (has_start_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->start_time(), target);
  }

  // required float end_time = 6;
  if (has_end_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->end_time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ProInnerMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 session_id = 1;
    if (has_session_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->session_id());
    }

    // required int32 message_type = 2;
    if (has_message_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->message_type());
    }

    // required int32 content_type = 3;
    if (has_content_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->content_type());
    }

    // required int32 content_length = 4;
    if (has_content_length()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->content_length());
    }

    // required float start_time = 5;
    if (has_start_time()) {
      total_size += 1 + 4;
    }

    // required float end_time = 6;
    if (has_end_time()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProInnerMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ProInnerMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ProInnerMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProInnerMessage::MergeFrom(const ProInnerMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_id()) {
      set_session_id(from.session_id());
    }
    if (from.has_message_type()) {
      set_message_type(from.message_type());
    }
    if (from.has_content_type()) {
      set_content_type(from.content_type());
    }
    if (from.has_content_length()) {
      set_content_length(from.content_length());
    }
    if (from.has_start_time()) {
      set_start_time(from.start_time());
    }
    if (from.has_end_time()) {
      set_end_time(from.end_time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ProInnerMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProInnerMessage::CopyFrom(const ProInnerMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProInnerMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  return true;
}

void ProInnerMessage::Swap(ProInnerMessage* other) {
  if (other != this) {
    std::swap(session_id_, other->session_id_);
    std::swap(message_type_, other->message_type_);
    std::swap(content_type_, other->content_type_);
    std::swap(content_length_, other->content_length_);
    std::swap(start_time_, other->start_time_);
    std::swap(end_time_, other->end_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ProInnerMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProInnerMessage_descriptor_;
  metadata.reflection = ProInnerMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace leopardIO

// @@protoc_insertion_point(global_scope)
